name: devcontainer-fomaud-dockerhub

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "42 4 * * *"
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  IMAGE_BASENAME: fomaud
  DOCKERHUB_USER: takker289
  DOCKERHUB_REPO: devenv

jobs:
  push_fomaud_to_dockerhub:
    name: Push ${IMAGE_BASENAME} images to dockerhub
    strategy:
      matrix:
        DIST: [debian, ubuntu]
        include:
          - DIST: debian
            VARIANT: stable
          - DIST: debian
            VARIANT: bookworm
          - DIST: debian
            VARIANT: trixie
          - DIST: ubuntu
            VARIANT: jammy
          - DIST: ubuntu
            VARIANT: noble
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to the Github Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_BASENAME }}-${{ matrix.DIST }}.${{ matrix.VARIANT }}
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:devcontainer/${{ env.IMAGE_BASENAME }}"
        push: true
        build-args: |
          DIST=${{ matrix.DIST }}
          VARIANT=${{ matrix.VARIANT }}
        tags: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_BASENAME }}-${{ matrix.DIST }}.${{ matrix.VARIANT }}
