name: devcontainer-java

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "48 4 * * *"
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  IMAGE_BASENAME: java
  DOCKERHUB_USER: takker289
  DOCKERHUB_REPO: devenv
  GITHUB_REPOSITORY: ghcr.io
  GITHUB_USER: tak289
  GITHUB_REPO: devenv

jobs:
  push_java_to_repositories:
    name: Push ${IMAGE_BASENAME} images to repositories
    strategy:
      matrix:
        include:
          - DIST: debian
            VARIANT: stable
            JAVA_VENDOR: openjdk
            JAVA_VERSION: 17
            JAVA_VARIANT: jdk
          - DIST: debian
            VARIANT: trixie
            JAVA_VENDOR: openjdk
            JAVA_VERSION: 17
            JAVA_VARIANT: jdk
          - DIST: ubuntu
            VARIANT: noble
            JAVA_VENDOR: openjdk
            JAVA_VERSION: 17
            JAVA_VARIANT: jdk
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.GITHUB_REPOSITORY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push ${{ env.IMAGE_BASENAME }}-${{ matrix.DIST }}.${{ matrix.VARIANT }}
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: "{{defaultContext}}:devcontainer/${{ env.IMAGE_BASENAME }}"
          push: true
          build-args: |
            DIST=${{ matrix.DIST }}
            VARIANT=${{ matrix.VARIANT }}
            JAVA_VENDOR=${{ matrix.JAVA_VENDOR }}
            JAVA_VERSION=${{ matrix.JAVA_VERSION }}
            JAVA_VARIANT=${{ matrix.JAVA_VARIANT }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ env.GITHUB_REPOSITORY }}/${{ env.GITHUB_USER }}/${{ env.GITHUB_REPO }}:${{ matrix.JAVA_VENDOR }}${{ matrix.JAVA_VERSION }}-${{ matrix.DIST }}.${{ matrix.VARIANT }}
            ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}:${{ matrix.JAVA_VENDOR }}${{ matrix.JAVA_VERSION }}-${{ matrix.DIST }}.${{ matrix.VARIANT }}
