name: devcontainer-latex

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "44 4 * * *"
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push latex-debian.buster
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:devcontainer/latex"
        push: true
        build-args: |
          DIST=debian
          VARIANT=buster
        tags: takker289/devenv:latex-debian.buster
    - name: Build and push latex-debian.bookworm
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:devcontainer/latex"
        push: true
        build-args: |
          DIST=debian
          VARIANT=bookworm
        tags: takker289/devenv:latex-debian.bookworm
    - name: Build and push latex-debian.trixie
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:devcontainer/latex"
        push: true
        build-args: |
          DIST=debian
          VARIANT=trixie
        tags: takker289/devenv:latex-debian.trixie
    - name: Build and push latex-debian.stable
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:devcontainer/latex"
        push: true
        build-args: |
          DIST=debian
          VARIANT=stable
        tags: takker289/devenv:latex-debian.stable
